### ISSUE TITLE
Integrate FSM

### ISSUE THREAD

**Issue by Bathtor** [kompics/kompics#27]
Integrate Alex' FSM code (which I can't find...Alex, add a link pls).

**Comment by Bathtor** [comment]
We probably shouldn't close this until we get around the ktoolbox dependency in fsm implementation.

**Comment by o-alex** [comment]
dependency on ktoolbox removed - added [Identifier/Identifiable](https://github.com/kompics/kompics/commit/2c147302cce11c84d30152647a12d94f292ce905) to kompics core util.
