### ISSUE TITLE
Backport Netty

### ISSUE THREAD

**Issue by Bathtor** [kompics/kompics#36]
Since the Netty people thought it funny to abandon the `5.x` branch (yay), we should finally go ahead and backport the Netty Network component to the actively developed `4.x` branch. 

We've been falling behind security fixes, compatibility with newer JVM versions as well as SBT, etc.

**Comment by Bathtor** [comment]
There are bunch of deprecation warnings now in `NettNetwork.java`.
Can you please look into them @haraldng and see if we can rid of them, while you are at it?
I'll consider this part of this issue and reopen it for now.

**Comment by haraldng** [comment]
@Bathtor I have fixed all the deprecated warnings in NettyNetwork.java apart from the ones related to UDT. Netty will not maintain UDT transport anymore and there are no replacements. Should I just leave them?

**Comment by Bathtor** [comment]
Hmm, yeah, I wanna keep UDT. Just add `@SuppressWarnings( "deprecation" )` in all the relevant positions to make the warnings go away and do a PR, please :)
